apiVersion: v1
kind: Service
metadata:
  name: transformers-service
spec:
  selector:
    app: transformers
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30080
  type: LoadBalancer