"""initial migration

Revision ID: a103ad3bcd05
Revises: 
Create Date: 2024-10-24 08:10:34.452424

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a103ad3bcd05"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transformer", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transformer", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
