apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-addresspool-tf-cluster
  namespace: default
spec:
  addresses:
    - 10.0.0.7-10.0.0.9

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: default
spec:
  ipAddressPools:
  - ip-addresspool-tf-cluster

